// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Identity interface {
	IsIdentity()
}

type User struct {
	ID       string `json:"id"`
	Username string `json:"username"`
}

func (User) IsIdentity() {}
func (User) IsEntity()   {}
